Models/Departamento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaPaginacionDept.Models
{
    [Table("DEPT")]
    public class Departamento
    {
        [Key]
        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }        
        [Column("DNOMBRE")]
        public string Nombre { get; set; }        
        [Column("LOC")]
        public string Localidad { get; set; }
    }
}

Models/Empleado.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace PracticaPaginacionDept.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }     
        [Column("OFICIO")]
        public string Oficio { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }
    }
}

Models/EmpleadoPaginacion.cs
namespace PracticaPaginacionDept.Models
{
    public class EmpleadoPaginacion
    {
        public int Registros { get; set; }
        public Empleado Empleado { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace PracticaPaginacionDept.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PracticaPaginacionDept.Models;
using PracticaPaginacionDept.Repositories;

namespace PracticaPaginacionDept.Controllers
{
    public class DepartamentoController : Controller
    {
        private RepositoryDepartamento repo;
        public DepartamentoController(RepositoryDepartamento repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Departamentos()
        {
            List<Departamento> departamentos = await this.repo.GetDepartamentosAsync();
            return View(departamentos);
        }
        public async Task<IActionResult> EmpleadosDepartamento
        (int? posicion, int iddepartamento)
        {
            if (posicion == null)
            {
                //POSICION PARA EL EMPLEADO
                posicion = 1;
            }
            EmpleadoPaginacion model = await
                this.repo.GetEmpleadoDepartamentoAsync
                (posicion.Value, iddepartamento);
            Departamento departamento =
                await this.repo.FindDepartamentoAsync(iddepartamento);
            ViewData["DEPARTAMENTOSELECCIONADO"] = departamento;
            ViewData["REGISTROS"] = model.Registros;
            ViewData["DEPARTAMENTO"] = iddepartamento;
            int siguiente = posicion.Value + 1;
            //DEBEMOS COMPROBAR QUE NO PASAMOS DEL NUMERO DE REGISTROS
            if (siguiente > model.Registros)
            {
                //EFECTO OPTICO
                siguiente = model.Registros;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["ULTIMO"] = model.Registros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;
            return View(model.Empleado);
        }


        public async Task<IActionResult> _PaginacionPartial
(int? posicion, int iddepartamento)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            EmpleadoPaginacion model = await
                this.repo.GetEmpleadoDepartamentoAsync
                (posicion.Value, iddepartamento);
            Departamento departamento =
                await this.repo.FindDepartamentoAsync(iddepartamento);
            ViewData["DEPARTAMENTOSELECCIONADO"] = departamento;
            ViewData["REGISTROS"] = model.Registros;
            ViewData["DEPARTAMENTO"] = iddepartamento;
            int siguiente = posicion.Value + 1;
            if (siguiente > model.Registros)
            {
                siguiente = model.Registros;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["ULTIMO"] = model.Registros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;
            return PartialView("_PaginacionPartial", model.Empleado);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaPaginacionDept.Models;
using System.Diagnostics;

namespace PracticaPaginacionDept.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Departamento/Departamentos.cshtml
@{
    ViewData["Title"] = "Departamentos";
}

@model List<Departamento>

<h1>Paginacion Empleados Departamento</h1>

<ul class="list-group">
    @foreach (Departamento dept in Model)
    {
        <li class="list-group-item">
            <a asp-controller="Departamento"
               asp-action="EmpleadosDepartamento"
               asp-route-iddepartamento="@dept.IdDepartamento">
                @dept.Nombre
            </a>
        </li>
    }
</ul>

Views/Departamento/EmpleadosDepartamento.cshtml
@{
    ViewData["Title"] = "Departamentos";
}

@model Empleado

@{
    Departamento departamento =
            ViewData["DEPARTAMENTOSELECCIONADO"] as Departamento;
}

<h1>Departamentos</h1>
<p>
    <a asp-controller="Departamento"
       asp-action="Departamentos">
        Volver a departamentos
    </a>
</p>

<ul class="list-group">
    <li class="list-group-item list-group-item-danger">
        Id Departamento: @departamento.IdDepartamento
    </li>
    <li class="list-group-item list-group-item-info">
        Nombre: @departamento.Nombre
    </li>
    <li class="list-group-item list-group-item-info">
        Localidad: @departamento.Localidad
    </li>
</ul>

<hr />
<div id="partialEmpleados"></div>

@section Scripts {
    <script>
        function loadEmpleadoPaginacion(posicion) {
            $(document).ready(function () {
                $("#partialEmpleados").load("/Departamento/_PaginacionPartial?posicion="
                    + posicion + "&iddepartamento=" + @departamento.IdDepartamento);
            });
        }

        loadEmpleadoPaginacion(1);
    </script>
}

Views/Departamento/_PaginacionPartial.cshtml
@{
    ViewData["Title"] = "_PaginacionPartial";
}

@model Empleado

@{
    Departamento departamento =
            ViewData["DEPARTAMENTOSELECCIONADO"] as Departamento;
}
<h3 class="mt-3">@ViewData["POSICION"] de @ViewData["ULTIMO"]</h3>

<ul class="list-group list-group-horizontal">
    <li class="list-group-item">
        <button class="btn btn-dark" onclick="loadEmpleadoPaginacion(1)" id="primero">
            Primero
        </button>
    </li>
    <li class="list-group-item">
        <button class="btn btn-dark" onclick="loadEmpleadoPaginacion(@ViewData["ANTERIOR"])" id="anterior">
            Anterior
        </button>
    </li>
    <li class="list-group-item">
        <button class="btn btn-dark" onclick="loadEmpleadoPaginacion(@ViewData["SIGUIENTE"])" id="siguiente">
            Siguiente
        </button>
    </li>
    <li class="list-group-item">
        <button class="btn btn-dark" onclick="loadEmpleadoPaginacion(@ViewData["ULTIMO"])" id="ultimo">
            Ultimo
        </button>
    </li>
</ul>

<ul class="list-group" id="detalleempleado">
    <li class="list-group-item list-group-item-info">
        Id Empleado: @Model.IdEmpleado
    </li>
    <li class="list-group-item list-group-item-info">
        Apellido: @Model.Apellido
    </li>
    <li class="list-group-item list-group-item-info">
        Oficio: @Model.Oficio
    </li>
    <li class="list-group-item list-group-item-info">
        Salario: @Model.Salario
    </li>
    <li class="list-group-item list-group-item-info">
        Departamento: @Model.IdDepartamento
    </li>
</ul>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaPaginacionDept</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaPaginacionDept.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaPaginacionDept</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="Departamentos">Departamentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PracticaPaginacionDept - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>